import { HttpStatus } from '@nestjs/common';

export const ERROR_CODE = {
  DUPLICATED_ERROR: 'DUPLICATED_ERROR',
  FOREIGNKEY_ERROR: 'FOREIGNKEY_ERROR',
  NOTNULL_ERROR: 'NOTNULL_ERROR',
  DB_ERROR: 'DB_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DEFINED_ERROR: 'DEFINED_ERROR',
} as const;

export type TErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export const ERROR_CODE_STATUS_MAPPING = {
  DUPLICATED_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  FOREIGNKEY_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  NOTNULL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  DB_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  INTERNAL_SERVER_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  DEFINED_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
} as const;
