import { HttpStatus } from '@nestjs/common';

export const ERROR_CODE = {
  DUPLICATED_EMAIL: 'DUPLICATED_EMAIL',
  DB_ERROR: 'DB_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  NOT_FOUND_USER: 'NOT_FOUND_USER',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESTRICT_SIGNIN: 'RESTRICT_SIGNIN',
  DEFINED_ERROR: 'DEFINED_ERROR',
} as const;

export type TErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export const ERROR_CODE_STATUS_MAPPING = {
  DUPLICATED_EMAIL: HttpStatus.CONFLICT,
  DB_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  INTERNAL_SERVER_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  NOT_AUTHORIZED: HttpStatus.FORBIDDEN,
  NOT_FOUND_USER: HttpStatus.NOT_FOUND,
  INVALID_PASSWORD: HttpStatus.BAD_REQUEST,
  SAME_PASSWORD: HttpStatus.BAD_REQUEST,
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  RESTRICT_SIGNIN: HttpStatus.TOO_MANY_REQUESTS,
  DEFINED_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
} as const;
